export enum ApiError {
    Generic = 0,

    _Unknown = 1000,
    UnknownUser,
    UnknownCategory,
    UnknownPost,
    UnknownPostReply,
    UnknownMessage,

    _Validations = 2000,
    InvalidObject,
    BadUsernameFormat,
    BadEmailFormat,
    BadPasswordFormat,
    InvalidAuthorization,
    InvalidEmail,
    InvalidPassword,
    InvalidCategoryName,
    InvalidPostTitle,

    _Limitations = 3000,
    NotStudentOrTeacher,
    UsernameUnavailable,
    EmailTaken,
    BadUsernameLength,
    BadPasswordLength,
    NewPasswordIsCurrent,
    BadCategoryNameLength,
    BadCategoryDescriptionLength,
    BadPostTitleLength,
    BadMessageContentLength,

    _Permissions = 4000,
    NoPermission,
    CategoryLocked,
    PostLocked,
}
